server:
  type: simple
  applicationContextPath: /file-indexer
  adminContextPath: /file-indexer/admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  loggers:
    com.hevo:
      level: TRACE
  appenders:
    - type: console

elasticSearchDb:
  hostname: http://localhost:9200
  fileInfoIndex: file-info

s3Buckets:
  fileBucket: hevo-test-files

s3ChangelogConsumer:
  queueName: s3-file-info-changelog
